/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as InstallRouteImport } from './routes/install'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CardCardIdRouteImport } from './routes/card.$cardId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiNativeExchangeRouteImport } from './routes/api/native/exchange'
import { Route as ApiNativeKeysRouteImport } from './routes/api/native/keys'
import { Route as ApiNativeOauthRouteImport } from './routes/api/native/oauth'
import { Route as ApiNativeScanRouteImport } from './routes/api/native/scan'
import { Route as ApiNativeSessionRouteImport } from './routes/api/native/session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CardCardIdRoute = CardCardIdRouteImport.update({
  id: '/card/$cardId',
  path: '/card/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNativeExchangeRoute = ApiNativeExchangeRouteImport.update({
  id: '/api/native/exchange',
  path: '/api/native/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNativeKeysRoute = ApiNativeKeysRouteImport.update({
  id: '/api/native/keys',
  path: '/api/native/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNativeOauthRoute = ApiNativeOauthRouteImport.update({
  id: '/api/native/oauth',
  path: '/api/native/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNativeScanRoute = ApiNativeScanRouteImport.update({
  id: '/api/native/scan',
  path: '/api/native/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNativeSessionRoute = ApiNativeSessionRouteImport.update({
  id: '/api/native/session',
  path: '/api/native/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/card/$cardId': typeof CardCardIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/native/exchange': typeof ApiNativeExchangeRoute
  '/api/native/keys': typeof ApiNativeKeysRoute
  '/api/native/oauth': typeof ApiNativeOauthRoute
  '/api/native/scan': typeof ApiNativeScanRoute
  '/api/native/session': typeof ApiNativeSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/card/$cardId': typeof CardCardIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/native/exchange': typeof ApiNativeExchangeRoute
  '/api/native/keys': typeof ApiNativeKeysRoute
  '/api/native/oauth': typeof ApiNativeOauthRoute
  '/api/native/scan': typeof ApiNativeScanRoute
  '/api/native/session': typeof ApiNativeSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/card/$cardId': typeof CardCardIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/native/exchange': typeof ApiNativeExchangeRoute
  '/api/native/keys': typeof ApiNativeKeysRoute
  '/api/native/oauth': typeof ApiNativeOauthRoute
  '/api/native/scan': typeof ApiNativeScanRoute
  '/api/native/session': typeof ApiNativeSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/install'
    | '/login'
    | '/privacy'
    | '/privacy-policy'
    | '/saved'
    | '/settings'
    | '/card/$cardId'
    | '/api/auth/$'
    | '/api/native/exchange'
    | '/api/native/keys'
    | '/api/native/oauth'
    | '/api/native/scan'
    | '/api/native/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/install'
    | '/login'
    | '/privacy'
    | '/privacy-policy'
    | '/saved'
    | '/settings'
    | '/card/$cardId'
    | '/api/auth/$'
    | '/api/native/exchange'
    | '/api/native/keys'
    | '/api/native/oauth'
    | '/api/native/scan'
    | '/api/native/session'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/install'
    | '/login'
    | '/privacy'
    | '/privacy-policy'
    | '/saved'
    | '/settings'
    | '/card/$cardId'
    | '/api/auth/$'
    | '/api/native/exchange'
    | '/api/native/keys'
    | '/api/native/oauth'
    | '/api/native/scan'
    | '/api/native/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  InstallRoute: typeof InstallRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  CardCardIdRoute: typeof CardCardIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNativeExchangeRoute: typeof ApiNativeExchangeRoute
  ApiNativeKeysRoute: typeof ApiNativeKeysRoute
  ApiNativeOauthRoute: typeof ApiNativeOauthRoute
  ApiNativeScanRoute: typeof ApiNativeScanRoute
  ApiNativeSessionRoute: typeof ApiNativeSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$cardId': {
      id: '/card/$cardId'
      path: '/card/$cardId'
      fullPath: '/card/$cardId'
      preLoaderRoute: typeof CardCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/native/exchange': {
      id: '/api/native/exchange'
      path: '/api/native/exchange'
      fullPath: '/api/native/exchange'
      preLoaderRoute: typeof ApiNativeExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/native/keys': {
      id: '/api/native/keys'
      path: '/api/native/keys'
      fullPath: '/api/native/keys'
      preLoaderRoute: typeof ApiNativeKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/native/oauth': {
      id: '/api/native/oauth'
      path: '/api/native/oauth'
      fullPath: '/api/native/oauth'
      preLoaderRoute: typeof ApiNativeOauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/native/scan': {
      id: '/api/native/scan'
      path: '/api/native/scan'
      fullPath: '/api/native/scan'
      preLoaderRoute: typeof ApiNativeScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/native/session': {
      id: '/api/native/session'
      path: '/api/native/session'
      fullPath: '/api/native/session'
      preLoaderRoute: typeof ApiNativeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  InstallRoute: InstallRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  CardCardIdRoute: CardCardIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNativeExchangeRoute: ApiNativeExchangeRoute,
  ApiNativeKeysRoute: ApiNativeKeysRoute,
  ApiNativeOauthRoute: ApiNativeOauthRoute,
  ApiNativeScanRoute: ApiNativeScanRoute,
  ApiNativeSessionRoute: ApiNativeSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
